
which calendar 2>&1 >/dev/null && \
for i in {1..$COLUMNS} ; do echo -n "_" ; done && \
echo && \
calendar -A0 | sed "s/^\(......\*.*\)/[1m\1[0m/" && \
for i in {1..$COLUMNS} ; do echo -n "_" ; done && \
echo "[0m"


